### ISSUE TITLE
Aufblinken der Sprachauswahl bei Stadtwechsel umgehen

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/app-android#108]
Wenn ich eine Stadt und Sprache ausgewählt habe und den Ort ändere, blinkt die Sprachauswahl kurz auf und verschwindet dann. 
Zum Beispiel:

1. Augsburg wählen 
2. Deutsch wählen 
3. Ort ändern
4. Bad Tölz 

-> Sprachauswahl blinkt kurz auf, dann wird aber direkt der Inhalt geladen

**Comment by ammyg** [comment]
Die Sprachauswahl wird nur noch angezeigt, wenn die alte Sprache nicht in
der neuen Stadt existiert. Ansonsten wählt er automatisch die Alte.

Martin Schrimpf <notifications@github.com> schrieb am Do., 19. Nov. 2015
11:16:

**Comment by Meash** [comment]
Ah super, passt.
Kann man das aufblinken noch umgehen?

**Comment by Dalanie** [comment]
Hab ich was verpasst oder betrifft das nicht die aktuelle Version? Kann es nicht reproduzieren.

**Comment by ammyg** [comment]
Das habe ich im Branch newfeature/welcomescreen implementiert. Im Master-Branch ist es noch nicht drin. Wir könnten den Welcome-Screen mit Leben füllen und dann in den master-Branch mergen.

Das Aufblinken zu verhindern ist ja an sich kein Problem ;).

**Comment by Dalanie** [comment]
Klingt gut, kuemmerst du dich ums Leben? Muesste wohl hardgecoded sein und in allen bisher angebotenen Sprachen existieren - oder was war unser aktueller Stand?

**Comment by ammyg** [comment]
Ich kümmere mich drum. Hardgecoded ist am einfachsten und wenn wir keine Stadtspezifischen Seiten machen auch durchaus sinnvoll.
