### ISSUE TITLE
PDFs offline speichern 

### ISSUE THREAD

**Issue by mschrimpf** [Integreat/app-android#123]
Anregung von Julia Hüther: Verlinkte PDFs im Text offline verfügbar machen

**Comment by Dalanie** [comment]
Verstehe nicht genau,was damit gemeint ist? Pdfs in nem externen PDF Viewer öffnen? Pdfs beim Laden der Seite ebenfalls herunterladen? (Was bei vielen Verlinkungen wirklich ewig dauern kann)

**Comment by Meash** [comment]
Würde sagen, dass wir die PDF links, die auf unsere Domain zeigen, cachen.
Neu cachen dann beim update der Page, die darauf zeigt. Könnte man in der
App noch mit einem PDF Symbol o.ä. kenntlich machen.

Hintergrund ist, dass im cms hochgeladene PDFs auf dem Server gespeichert
werden und dann aus der Seite darauf verlinkt wird. Diese Dateien könnte
man sonst nur mit Internet anschauen.

**Comment by Dalanie** [comment]
für jemanden, der es implementieren möchte: http://stackoverflow.com/a/17095159/1484047

**Comment by Lemming0815** [comment]
Dann fehlt uns aber die Kontrolle darüber, wie groß und wie viele Dateien das werden.
Ich verstehe jetzt, dass 
a) alle pdfs automatisch runtergeladen werden, sobald man die Seite mit Internet öffnen? Oder
b) explizit zum ersten mal, wenn man die pdf öffnen will und ab da für die Zukunft cachen?
c) neue Idee: wie bei maps.me eine Art store für alle Dokumente, die man in einer Übersicht einzeln oder komplett downloaden kann.

a) hat den Nachteil von unkontrollierter Datenmenge, die das erste öffnen doch stark ausbremsen kann (nicht alle hotspots haben viel bandbreite), außerdem haben günstige Smartphones nicht besonders viel Platz, b) hat den nachteil, dass man erst nach einiger Zeit darauf stößt und dann wahrscheinlich grad kein Internet hat. c) hat den Nachteil, dass man die Funktion erst finden muss. DIe app wird evtl. unnötig komplex, aber den Vorteil, die Datenmengen gut zu kontrollieren und zukünftig die Dokumente zu verwalten (öffnen, löschen, sharen)

**Comment by Meash** [comment]
Es geht nur um die PDFs, die explizit in unsere Plattform hochgeladen
wurden.
Würde vermuten, dass die Datenmenge nicht zu groß wird, paar MB vielleicht
(eine PDF ist in der Regel im 2-3 stelligen KB Bereich).

Sonst muss man im cms darauf hinweisen, dass PDFs nicht offline verfügbar
sind. @Dalanie wie siehst du das?

**Comment by Dalanie** [comment]
Durchaus moeglich. Technologisch am einfachsten waere es jedoch, wenn man
die PDFs einfach Cached beim ersten Aufruf und nicht vorlaedt. Aendern die
sich, sollte man jedoch den Pfad anpassen, da die meisten Caching
Frameworks einfach die URL nehmen.

Man kann natuerlich aber auch (mit deutlich mehr Aufwand) selbst seine
eigene Caching-Strategie umsetzen und Daten beim ersten Laden der App
herunterladen.

Wie sieht es bei den Files mit Mehrsprachigkeit aus? Verweisen sie auf
unterschiedliche Dateien?


Wie waere es mit einer Frage am Anfang beim initialen Start: Dateien
mitladen?

**Comment by Lemming0815** [comment]
Ob diese Frage dann jeder versteht, der die app zum ersten mal startet?

**Comment by visi0nary** [comment]
@Dalanie Direkt mit Fragen anfangen finde ich auch immer eher abschreckend. Ich würde das - wenn es die Option geben sollte - in die Einstellungen packen.

**Comment by Meash** [comment]
Finde Fragen auch eher störend.
Mehrsprachigkeit sollte der Caching Strategie egal sein: sie sollte beim Laden der Daten gleichzeitig externe Links durchforsten und wenn die auf unsere eigene Domain zeigen, die Daten cachen.

**Comment by Dalanie** [comment]
Das koennen u.U. aber auch gut mehrere MegaByte werden..

**Comment by Meash** [comment]
Jo.
Soviel PDFs sollten es normal aber auch nicht werden.

**Comment by Lemming0815** [comment]
Keep It simple... M.E. wäre ein Download Button in den settings am sinnvollsten

**Comment by Meash** [comment]
Das Hauptargument ist, dass die PDFs offline verfügbar sein sollen - ein Direct Link scheidet daher aus.

**Comment by dkehne** [comment]
Sollten wir umsetzen, sobald wir können. Wie ist der Stand?

**Comment by Dalanie** [comment]
Implemeted - bitte im beta-channel checken ;)
