### ISSUE TITLE
Use card views for implementing categories

### ISSUE THREAD

**Issue by visi0nary** [Integreat/app-android#129]
What about using the card views that are also used in e.g. Google Keep to create two columns with 8 categories as it is done in the UI mockup?

**Comment by Dalanie** [comment]
Sounds good

**Comment by Lemming0815** [comment]
which mockup are your referring to?
I am not sure if I understand correctly but I would not prefer having two columns. Rather one column and all items listed. much cleaner look.

**Comment by Dalanie** [comment]
I thought with categories he means the categories from events. The "main"
list already offers two columns, when switched to landscape mode
