### ISSUE TITLE
Datumsanzeige im Menü nach Sprachauswahl

### ISSUE THREAD

**Issue by julia-goetz** [Integreat/app-android#139]
Es wird noch ein (Seitenbearbeitungs-?) Datum angezeigt zu den jeweiligen Pages, gerne ersetzen durch farbliche Markierung o.ä. falls etwas geändert wurde seit letztem Besuch.

**Comment by Dalanie** [comment]
habs jetzt rausgenommen - farbliche markierung kann man natürlich noch einbauen, falls gewünscht, sollt man nochmal drüber reden
