### ISSUE TITLE
Asynchronität zwischen CMS und App | Landkreis Germersheim

### ISSUE THREAD

**Issue by dkehne** [Integreat/app-android#161]
Problem in Germersheim: In der App sind andere Inhalte als im CMS. Da sind einach mal zwei Seiten in der App, die im CMS nicht vorhanden sind. Die bekommt man auhc nicht mit normalen Refresh raus. Kann jetzt schlecht der Verwaltung sagen sie sollen ihren Cache leeren....

![photo_2016-02-16_14-43-44](https://cloud.githubusercontent.com/assets/4182469/13077857/b34a8e2e-d4bb-11e5-9ddb-a6f39267c57e.jpg)

**Comment by Dalanie** [comment]
Ich krieg beim Initialen laden auch andere Seiten. Scheinbar liefert das
cms diese aus (ich vermute mal es sind gelöschte Seiten)?

**Comment by sven15** [comment]
Ähm ja, das CMS erlaubt derzeit das Löschen von Seiten. Bugfix ist schon eingereicht.

**Comment by sven15** [comment]
requires deployment of #312

**Comment by Dalanie** [comment]
Kann https://github.com/Integreat/app-android/issues/162 ebenfalls an dem Bug im CMS liegen?

**Comment by sven15** [comment]
äh ja. das problem kommt irgendwie durch das tree view. wenn man seiten verschiebt, muss man bei der übergeordneten seite noch mal "Aktualisieren" klicken, damit die hierarchie ordentlich gespeichert wird. dann zeigts das auch in der app korrekt an.
