### ISSUE TITLE
Asynchronität zwischen CMS und App | Gemeinde Kissing

### ISSUE THREAD

**Issue by dkehne** [Integreat/app-android#162]
In Kissing tauchen die als "Entwurf" markierten Seiten ganz oben in der App auf. Fehler ist urgent, da wir dort bereits Live sind und System ausgeilt wird.

![photo_2016-02-16_15-19-02](https://cloud.githubusercontent.com/assets/4182469/13078673/cf78ab26-d4c0-11e5-8062-a32b34175435.jpg)

**Comment by sven15** [comment]
Bitte Verwalter für Kissing

**Comment by dkehne** [comment]
bist verwalter.

**Comment by sven15** [comment]
Ich kann das bei mir nicht reproduzieren. Bei mir sehe ich nur veröffentlichte Artikel

**Comment by Dalanie** [comment]
Kann es bei mir auch nicht reproduzieren. Welche Version nutzt du? Bist du
bei der beta angemeldet?

**Comment by dkehne** [comment]
Version buddy

**Comment by Dalanie** [comment]
Nutze ich auch...  Scheint eventuell das Updaten von Einträgen fehlerhaft
zu sein? Wenn ich den content frisch lade, zeigt er nur die richtigen
Einträge an

**Comment by dkehne** [comment]
Scheint so....Also bei mir hilft kein Refresh, Flugzeugmodus oder Switch von WLAN/Mobil. Cache leeren mache ich mal bewusst nicht....

**Comment by Dalanie** [comment]
Ich kann es nicht reproduzieren :/ Weiß nicht was ich da gerade machen soll/kann. Es scheint ja bei anderen Instanzen kein Fehler aufzutreten - sicher dass da im CMS nicht irgendwas falsch gesetzt ist?

**Comment by dkehne** [comment]
Kam noch keine Beschwerde. VIelleicht liegt es an meinem Client....
