### ISSUE TITLE
Refresh des Stadtlogos ohne Cache-Leerung

### ISSUE THREAD

**Issue by dkehne** [Integreat/app-android#163]
Einige Städte erarbeiten gerade ihre Inhalte und haben mit der DeutschlandInstsanz (Brandenburger Tor) angefangen. Jetzt haben wir ihre Logos eingepflegt aber eine einfache Aktualisierung reicht nicht. Cache leeren oder Neuinstallation eventuell nicht die optimale Lösung. Ist das viel Aufwand auch das Titltebild auf "Change" zu checken?

**Comment by Dalanie** [comment]
Hm, wird eventuell für das neue Logo der gleiche link ausgeliefert? Dann
wird Android denken "oh, das Bild hab ich bereits"  und es nicht
herunterladen.

Wenn das Bild einen anderen link hat, dann stimmt die Aktualisierung
derzeit nicht.

**Comment by Dalanie** [comment]
@Meash  Kannst du mir mehr verraten was bei nem "Aendern des Bildes" passiert? Wird die URL geaendert oder nur das Bild?

**Comment by Meash** [comment]
URL wird normal auch geändert.
Es gibt aber einen Spezialfall: wenn man das alte Bild löscht und ein neues
mit genau dem selben Namen hochlädt, ändert sich das Bild und die URL nicht.

**Comment by dkehne** [comment]
Spezialfall lag hier nicht vor.

**Comment by Dalanie** [comment]
Ich hab nur noch eine Theorie. Kannst du mal bitte die Stadt wechseln, zu der Seitenansicht gehen und dann zurück zu der alten Instanz? Daran kann es liegen dass er die alten Daten noch verwendet. Ansonsten sollte nen "Force Refresh" (bei der Stadtauswahl mal herunterswipen und "neuladen") ausreichen. Zeigt er das nur in der Seitenübersicht falsch an oder auch bei der Stadtauswahl?

Wäre die einzige Erklärung da die Stadt selbst nie neugeladen wird wenn man die Instanz nicht wechselt (und ergo auch nie andere Bilder/Namen/Farbe bekommt). Fände das auch eher kontraproduktiv da nen Refresh einzubauen wenn sich die Stadt in 99,9% der Zeit nie ändert... :O

**Comment by dkehne** [comment]
Okay der Refresh hat funktioniert! Danke passt.

**Comment by Dalanie** [comment]
Was davon hat funktioniert? der Force Refresh oder das Wechseln des Ortes?

**Comment by dkehne** [comment]
Der Refresh auf der Ort-Wechsel-Seite.
