### ISSUE TITLE
Credits für flaticon.com hardcoded oder über CMS?

### ISSUE THREAD

**Issue by dkehne** [Integreat/app-android#164]
Hey all,

for the usage of our current icon set, we need to have a premium plan from flaticon.com which leads to annual costs and administration effort. But flaticon offered the following to us:

 	

```
Support (Flaticon)

Feb 18, 14:42

Hello Daniel,

Thank you very much for contacting us, we really appreciate the work that you are making and we feel really glad that you have choosed our services for it.

We are very sorry to inform you that we are not able to offer you a credit free plan for your project. The only offers we have are our subscription plans or the usage of our credits with attribution. If you desire, you may use all the icons you need from Flaticon on your app and insert the attribution *designed from Freepik by www.flaticon.com* on the app's description page and this way you will attribute correctly the usage of all the icons you have used.

Best regards and thank you for your comprehension, we wish you have a wonderful day!

Flaticon's Team.
```

So can we hardcode the credits into our app or shall we embed them into the imprint e.g in our Deutschland-Template and give the hint to local offices not to delete that in case of using the icons? If they would delete it, possible license penalites would target our project.

**Comment by Dalanie** [comment]
Don't they mean the app description in the playstore? Sounds like it

**Comment by dkehne** [comment]
Yeah you might be right. How can take responsibility? Task for our conference?

**Comment by Dalanie** [comment]
I don't think it's a big deal to just add it to the description. Anyone
with playstore credentials

**Comment by Dalanie** [comment]
I can add it into the disclamer as an own entry. Nobody is reading that anyways
