### ISSUE TITLE
"Remove all" Button?

### ISSUE THREAD

**Issue by Dalanie** [Integreat/app-android#166]
Does it make sense to have a "Remove all data" - Button? This would replace the "reinstall the app or empty your cache" workflow and would bring the users back to the Start Menu. This way we might avoid complications regarding the update (but of course this is just a workaround and not actually targeting the sync problem),

**Comment by Dalanie** [comment]
habs implementiert ;)

**Comment by sven15** [comment]
I sugggest we should think about a stateless synchronisation protocol.

**Comment by Dalanie** [comment]
Yes, true. We currently have a more or less "useful" sync protocol. In short: Check how old data is. If data is empty, do a full refresh. If data is older than X, do a refresh from everything newer than X. 

However, there are a few things that havent been covered: Changes are not directly reflected within the app (can be synced through force refresh by user).

What we could do is give the user the option to choose when syncing should happen (xamarin has the option to set sync to wifi only). Maybe options like: Every time I open the app, every x hours, everytime in wifi, but only every x hours with cell data..

**Comment by sven15** [comment]
How about the server sends a list of all page IDs with hashes or timestamps. If an ID does not show up anymore, the page can be deleted. And if a timestamp / hash does not match, the page has to be refreshed.

**Comment by Dalanie** [comment]
We already have this functionality to give us all updated/added/removed
pages since a certain point in time.

**Comment by Meash** [comment]
I think, things like new images are the problem, not pages, right?

**Comment by Dalanie** [comment]
Well the button does fix this problem as well (as long as you dont have the
same image url)
