### ISSUE TITLE
Implement new UI design

### ISSUE THREAD

**Issue by sven15** [Integreat/app-android#178]
Use the following images as a style reference for the new design.

![2 submenu_everyday life](https://cloud.githubusercontent.com/assets/15197000/13540528/6500c2c0-e257-11e5-85cc-9002cd82c065.png)
![3 detail view entry](https://cloud.githubusercontent.com/assets/15197000/13540529/651c99c8-e257-11e5-8dfe-ee603dec6444.png)
![1 main menu](https://cloud.githubusercontent.com/assets/15197000/13540530/655ccb92-e257-11e5-9cdd-945e5c39aea0.png)

**Comment by Meash** [comment]
We'll implement this in Xamarin: Integreat/app-cross_platform#44
