### ISSUE TITLE
Internal links not always working

### ISSUE THREAD

**Issue by sven15** [Integreat/app-android#180]
Internal links do not work all the time. 
There are 3 example links at the bottom of the following page:
https://cms.integreat-app.de/regensburg/de/ankunft-in-deutschland/ich-bin-in-der-erstaufnahmeeinrichtung-wer-kann-mir-helfen/
The first two links open a browser while the third link stays within Integreat.

**Comment by sven15** [comment]
HTML in web view:
<p><span style="color: black;font-family: 'Noto Serif';font-size: 13pt"> <strong>Test (wieder löschen!)<br />
</strong>&#8211; <a href="https://cms.integreat-app.de/regensburg/de/ankunft-in-deutschland/ich-bin-in-der-erstaufnahmeeinrichtung-wer-kann-mir-helfen/asyl-sozial-beratung/">Link zu Ebene 3</a><br />
&#8211; <a href="https://cms.integreat-app.de/regensburg/de/ankunft-in-deutschland/angebote-in-der-erstaufnahme-einrichtung/">Link zu Ebene 2</a><br />
&#8211; <a href="https://cms.integreat-app.de/regensburg/de/leben-in-regensburg/familie-und-kinder/">Funktionierender Link?</a><br />
</span></p>

**Comment by Dalanie** [comment]
Am I correct that the first two links are redirecting to a page that has
subpages? I did not consider that case I guess.. Might be a bit more
complicated

**Comment by sven15** [comment]
In case of "Link zu Ebene 2" yes, but not with the first link.

**Comment by Dalanie** [comment]
Sorry, I cannot find the page. I tried looking for keywords but all I can find is 'Wer kann mir helfen' with only one functional link (Migrationsdienste) and 'Ich lebe in einer Erstaufnahmeeinrichtung...'. Both don't have the links you described. All I can see is that everything seems to work fine...

https://cms.integreat-app.de/regensburg/de/ankunft-in-deutschland/ich-bin-in-der-erstaufnahmeeinrichtung-wer-kann-mir-helfen/ this page does not seem to exist neither does https://cms.integreat-app.de/regensburg/de/leben-in-regensburg/familie-und-kinder/ from the html link

**Comment by sven15** [comment]
Regensburg -> Deutsch -> (main menu) Ich bin ganz neu in Deutschland -> (2nd item in list) Ich lebe in einer Erstaufnahmeeinrichtung oder einer Notunterkunft - wer kann mir helfen? -> scroll to bottom of page.

The first two links open in browser, the third links to the in app page.
(Android 5.1.1, OxygenOS2.2.1-2)

**Comment by Dalanie** [comment]
I cannot reproduce it... I don't see these links - even with a newer version..

**Comment by sven15** [comment]
Everything seems to work.
