### ISSUE TITLE
Location images do not scale to required aspect ratio

### ISSUE THREAD

**Issue by sven15** [Integreat/app-android#181]
![screenshot_2016-05-16-10-16-22](https://cloud.githubusercontent.com/assets/15197000/15284712/559c164c-1b53-11e6-88d0-83bfb5fe2aa1.png)
(current beta)

**Comment by Dalanie** [comment]
Oh, that's bad. I'm on it!

**Comment by Dalanie** [comment]
fixed. uploading it to the beta track right now
