### ISSUE TITLE
Changing language within page not working

### ISSUE THREAD

**Issue by sven15** [Integreat/app-android#184]
As of 10330c0123372afbd51d14e1369b6a43c6da6eeb changing the language within a page is not possible.
It is however working in the list of pages.

**Comment by sven15** [comment]
Possibly due to changes in MyWebViewClient?
    public MyWebViewClient(Activity activity, Language language, Location location) {
        mActivityRef = new WeakReference<>(activity);
        RoboGuice.injectMembers(activity, this);
        mLanguage = language;
        mLocation = location;
    }

**Comment by sven15** [comment]
Fixed in current https://github.com/Integreat/app-android/tree/hierarchies branch.

**Comment by dlangerenken** [comment]
merged into base/master
